---
abstract: 'closures are objects are closures'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autobox-Closure-Attributes
no_index:
  directory:
    - inc
    - t
requires:
  PadWalker: 0
  autobox: 2.40
resources:
  homepage: http://github.com/sartak/autobox-Closure-Attributes/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/autobox-Closure-Attributes.git
version: 0.04
